apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server-blue
  namespace: guestbook-namespace
  labels:
    run: eureka-server-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      run: eureka-server-blue
  template:
    metadata:
      labels:
        run: eureka-server-blue
    spec:
      containers:
        - name: discovery-service
          image: liwei2151284.jfrog.io/docker-local/guestbook-microservices-k8s/discovery-service:8
          ports:
            - containerPort: 8761
              protocol: TCP
      imagePullSecrets:
        - name: regcred-local

