apiVersion: v1
kind: Service
metadata:
  name: discovery-service
  labels:
    run: discovery-service
spec:
  ports:
    - name: port1
      port: {{ .Values.discovery_service.port }}
      nodePort: {{ .Values.discovery_service.nodePort }}
      protocol: TCP
  selector:
    run: discovery-service
  type: NodePort
